### PR TITLE
packages.json and gulpfile.js updates

### PR DESCRIPTION
**Pull request by vjandrea**
Updated packages.json to use:
- npm 6.10.1
- gulp 4.0.2
- gulp-sass 4.0.2

Fixed gulpfile.js for compatibility with gulp^4.0, in particular using gulp.series() in place of arrays and fs.writeFileSync instead of fs.writeFile. Added also a return signal to modernizr task.

Final npm fixes to correct vulnerabilities.

### CODE REVIEW

**Comment by roffy2k** [comment]
Thanks - this is helping a lot. One thing though - "gulp watch" exits straight away. Any ideas what might be causing this? Happy to post further details if it would help.

**Comment by vjandrea** [comment]
Thanks @roffy2k, looks like an issue with `gulp-livereload`, I'll try to debug this. While I was debugging `npm install` I saw a notice about `livereload` being deprecated in favor of `gulp-refresh`, but I can't reproduce the message when I reapply each step to the original repo.

**Comment by vjandrea** [comment]
Hello @roffy2k please check the latest commits. I didn't squash so you can rollback single steps eventually.

**Comment by roffy2k** [comment]
That worked a treat! The only other thing I did was add {"node": true} to .jshintrc to make it behave a little better during the watch. Thanks @vjandrea.

**Comment by vjandrea** [comment]
@roffy2k please send a PR to my fork with your .jshintrc edit, so I can include it in this PR. Now hoping that someone among the mantainers will merge it.

**Comment by vjandrea** [comment]
@robertdevore any thoughts on this PR?

**Comment by mashirozx** [comment]
Thanks a lot! I googled for an hour before trying your branch… lol

**Pull request closed without merging**
