### PR TITLE
Add site icon support

### PR DESCRIPTION
**Pull request by mik-laj**
Related to: https://github.com/toddmotto/html5blank/issues/145

### CODE REVIEW

**Comment by oriSomething** [comment]
i haven't dig deep to this feature but it seems that calling to `wp_site_icon` is missing

**Comment by mik-laj** [comment]
https://core.trac.wordpress.org/changeset/32994
Look at this code. If  has_site_icon() is true, WP atuomatic add meta tags

**Comment by oriSomething** [comment]
@mik-laj Sorry for the delay. For some reasons I don't get some of the notifications in Github :/
Anyway, the `if` will be always `false` in old WP versions or an I miss something?

**Comment by robertdevore** [comment]
WordPress includes the site icon by default and will automatically add it as a favicon, so no additional work on the developers end is required.

See more info [here](https://www.sitepoint.com/all-you-need-to-know-about-the-new-wordpress-site-icon-api/)

**Pull request closed without merging**
